### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#10]
- [x] Ability to subscribe to errors specific to a compilation
- [x] Ability to watch directories from the core
- [x] Ability to add pre-compile hook and add support for babel
- [x] Ability to add post-compile hook and add support for uglify
- [x] Ability to generate sources and maps of selected modules in format of HMR or Bundle
- [x] Ability to generate sources and maps for all modules in format of Bundle
- [x] Middleware for express to serve latest compiled files
- [x] Ability to pass HMR callback on client side that determines how updates are applied
- [x] Ability to replace variables like `process.env` in the app
- [x] Ability to require node modules or their shims into the browser
- [x] Add a CLI package similar to webpack-dev-server
#### Removed Items
- ~~Ability to generate sources and maps of individual modules in format of HMR~~

**Comment by steelbrain** [comment]
All done :tada: :tada: :tada: :tada: :tada:
